name: CI
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest] # [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      WORKING_DIRECTORY_CLIENT: ./
      PROJECT_NAME: ${{ github.event.repository.name }}
    steps:
      - uses: actions/checkout@v2.4.0

#       # Define some variables that will be used.
#       - name: Define short sha variable
#         run: echo "SHORT_SHA=`git rev-parse --short HEAD`" >> $GITHUB_ENV
#       # view before
#       - name: Display the environment variables before
#         run: |
#           cat .env.production

      # Environment file override
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_VUE_APP_API_VERSION: ${{secrets.VUE_APP_API_VERSION}}
          envkey_VUE_APP_API_URL: ${{secrets.VUE_APP_API_URL}}
          directory: './'
          file_name: '.env'
      # view it after
      - name: Display the environment variables after
        run: |
          cat .env
      # Install 
      - name: Install build dependencies
        run: yarn install

      # Build it
      - name: Build it and they will come
        run: yarn build

      # Start tests          
      # TODO : Start up test server
      - name: Run tests          
        run: |
          cd ${{ env.WORKING_DIRECTORY }}
        working-directory: ${{env.WORKING_DIRECTORY}}
        env:
          NODE_ENV: test

      #------------------------------------
      # main branch deploy
      #------------------------------------
      - name: Create a Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          cd ${{ env.WORKING_DIRECTORY_API }}
          echo 'Placeholder for creating a semantic release - Left Blank on Purpose'
          
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.          

      #------------------------------------
      # develop branch
      #------------------------------------
      - name: Deploy to Staging
        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
        run: |
          cd ${{ env.WORKING_DIRECTORY_API }}
          echo 'Placeholder for sending to staging - Left Blank on Purpose'



